"""
Definicion unica de esquema para el dataset de BigQuery.
Cada entrada de TABLES es (nombre_tabla, lista_de_SchemaField, opciones_de_particion).

Diseno general:
- clients: dimension de clientes (soporta multiples clientes/verticales).
- assessments: una fila por "corrida" de una actividad para un cliente
  (liga consultor, fecha de revision y archivo origen con los datos de detalle).
- *_summary / *_recommendations / eva_*: tablas de hecho por actividad, todas
  referencian assessment_id.
- load_batches / rejected_rows: control de ingestas y filas con problemas.
"""

from google.cloud import bigquery

SchemaField = bigquery.SchemaField

TABLES = {
    "clients": {
        "schema": [
            SchemaField("client_id", "STRING", mode="REQUIRED"),
            SchemaField("client_name", "STRING", mode="REQUIRED"),
            SchemaField("vertical", "STRING"),
            SchemaField("created_at", "TIMESTAMP", mode="REQUIRED"),
        ],
    },
    "assessments": {
        "schema": [
            SchemaField("assessment_id", "STRING", mode="REQUIRED"),
            SchemaField("client_id", "STRING", mode="REQUIRED"),
            SchemaField("activity_type", "STRING", mode="REQUIRED"),
            SchemaField("consultant_name", "STRING"),
            SchemaField("profile_name", "STRING"),
            SchemaField("report_date", "DATE"),
            SchemaField("source_file", "STRING"),
            SchemaField("load_batch_id", "STRING"),
            SchemaField("created_at", "TIMESTAMP", mode="REQUIRED"),
        ],
        "time_partitioning": {"field": "report_date", "type_": "MONTH"},
        "clustering_fields": ["client_id", "activity_type"],
    },
    "email_filter_check_summary": {
        "schema": [
            SchemaField("assessment_id", "STRING", mode="REQUIRED"),
            SchemaField("domain", "STRING"),
            SchemaField("total_cyber_risk_pct", "FLOAT64"),
            SchemaField("total_cyber_risk_usd", "FLOAT64"),
            SchemaField("risk_rating", "STRING"),
            SchemaField("risk_rating_driver", "STRING"),
            SchemaField("email_filter_score_pct", "FLOAT64"),
            SchemaField("secure_config_score_pct", "FLOAT64"),
            SchemaField("open_relay_status", "STRING"),
            SchemaField("open_relay_pct", "FLOAT64"),
            SchemaField("spf_status", "STRING"),
            SchemaField("spf_pct", "FLOAT64"),
            SchemaField("dkim_status", "STRING"),
            SchemaField("dkim_pct", "FLOAT64"),
            SchemaField("dmarc_status", "STRING"),
            SchemaField("dmarc_pct", "FLOAT64"),
            SchemaField("mandatory_compliant", "INT64"),
            SchemaField("mandatory_noncompliant", "INT64"),
            SchemaField("mandatory_pct", "FLOAT64"),
            SchemaField("other_ext_compliant", "INT64"),
            SchemaField("other_ext_noncompliant", "INT64"),
            SchemaField("other_ext_pct", "FLOAT64"),
            SchemaField("other_ext_failing_list", "STRING"),
            SchemaField("total_risk_reduction_usd", "FLOAT64"),
        ],
        "clustering_fields": ["assessment_id"],
    },
    "email_filter_check_recommendations": {
        "schema": [
            SchemaField("assessment_id", "STRING", mode="REQUIRED"),
            SchemaField("rank", "INT64"),
            SchemaField("recommendation", "STRING"),
            SchemaField("current_safeguard_pct", "FLOAT64"),
            SchemaField("risk_reduction_usd", "FLOAT64"),
            SchemaField("cis_control", "STRING"),
        ],
        "clustering_fields": ["assessment_id"],
    },
    "domain_account_review_summary": {
        "schema": [
            SchemaField("assessment_id", "STRING", mode="REQUIRED"),
            SchemaField("execution_date", "DATE"),
            SchemaField("total_exposure_usd", "FLOAT64"),
            SchemaField("risk_rating", "STRING"),
            SchemaField("risk_rating_driver", "STRING"),
            SchemaField("accounts_evaluated", "INT64"),
            SchemaField("accounts_pwd_never_expire", "INT64"),
            SchemaField("accounts_no_pwd_required", "INT64"),
            SchemaField("dormant_60d", "INT64"),
            SchemaField("no_pwd_change_90d", "INT64"),
            SchemaField("generic_accounts", "INT64"),
            SchemaField("default_accounts", "INT64"),
            SchemaField("disabled_accounts", "INT64"),
            SchemaField("active_accounts", "INT64"),
            SchemaField("mfa_enrolled", "INT64"),
            SchemaField("mfa_enrolled_pct", "FLOAT64"),
            SchemaField("total_opportunity_usd", "FLOAT64"),
        ],
        "clustering_fields": ["assessment_id"],
    },
    "domain_account_review_recommendations": {
        "schema": [
            SchemaField("assessment_id", "STRING", mode="REQUIRED"),
            SchemaField("rank", "INT64"),
            SchemaField("recommendation", "STRING"),
            SchemaField("priority", "STRING"),
            SchemaField("detail", "STRING"),
        ],
        "clustering_fields": ["assessment_id"],
    },
    "eva_findings": {
        "schema": [
            SchemaField("assessment_id", "STRING", mode="REQUIRED"),
            SchemaField("host_ip", "STRING"),
            SchemaField("host_name", "STRING"),
            SchemaField("operating_system", "STRING"),
            SchemaField("system_type", "STRING"),
            SchemaField("original_severity", "STRING"),
            SchemaField("adjusted_severity", "STRING"),
            SchemaField("eol_reclassified", "BOOL"),
            SchemaField("vulnerability_name", "STRING"),
            SchemaField("synopsis", "STRING"),
            SchemaField("exploit_available", "BOOL"),
            SchemaField("eol_asset", "BOOL"),
            SchemaField("asset_criticality_tier", "STRING"),
            SchemaField("vulnerability_age", "STRING"),
            SchemaField("vuln_publication_date", "DATE"),
            SchemaField("plugin_publication_date", "DATE"),
            SchemaField("port", "STRING"),
            SchemaField("protocol", "STRING"),
            SchemaField("service", "STRING"),
            SchemaField("port_classification", "STRING"),
            SchemaField("scan_date", "DATE"),
            SchemaField("cis76_implementation_pct", "FLOAT64"),
            SchemaField("external_vm_risk_level", "STRING"),
        ],
        "time_partitioning": {"field": "scan_date", "type_": "MONTH"},
        "clustering_fields": ["assessment_id", "adjusted_severity"],
    },
    "eva_vulnerability_aging": {
        "schema": [
            SchemaField("assessment_id", "STRING", mode="REQUIRED"),
            SchemaField("host_ip", "STRING"),
            SchemaField("host_name", "STRING"),
            SchemaField("operating_system", "STRING"),
            SchemaField("system_type", "STRING"),
            SchemaField("asset_criticality", "STRING"),
            SchemaField("port", "STRING"),
            SchemaField("protocol", "STRING"),
            SchemaField("adjusted_severity", "STRING"),
            SchemaField("vulnerability_name", "STRING"),
            SchemaField("cve", "STRING"),
            SchemaField("vuln_publication_date", "DATE"),
            SchemaField("plugin_publication_date", "DATE"),
            SchemaField("scan_date", "DATE"),
            SchemaField("age_years_label", "STRING"),
            SchemaField("age_years_numeric", "FLOAT64"),
            SchemaField("age_bucket", "STRING"),
            SchemaField("days_since_publication", "INT64"),
            SchemaField("exceeds_90_day_sla", "BOOL"),
            SchemaField("exceeds_365_day_sla", "BOOL"),
            SchemaField("eol_asset", "BOOL"),
            SchemaField("exploit_available", "BOOL"),
            SchemaField("remediation_priority", "STRING"),
        ],
        "time_partitioning": {"field": "scan_date", "type_": "MONTH"},
        "clustering_fields": ["assessment_id", "remediation_priority"],
    },
    "eva_top10_recommendations": {
        "schema": [
            SchemaField("assessment_id", "STRING", mode="REQUIRED"),
            SchemaField("rank", "INT64"),
            SchemaField("severity_addressed", "STRING"),
            SchemaField("recommendation", "STRING"),
            SchemaField("description", "STRING"),
            SchemaField("affected_assets", "STRING"),
            SchemaField("operating_system", "STRING"),
            SchemaField("open_insecure_ports", "STRING"),
            SchemaField("cve", "STRING"),
            SchemaField("eol_asset", "STRING"),
            SchemaField("exploit_available", "STRING"),
            SchemaField("vulnerabilities_addressed", "STRING"),
            SchemaField("risk_reduction_estimate_usd", "FLOAT64"),
            SchemaField("primary_loss_driver", "STRING"),
            SchemaField("secondary_loss_driver", "STRING"),
            SchemaField("cis_control", "STRING"),
            SchemaField("remediation_complexity", "STRING"),
            SchemaField("remediation_timeline", "STRING"),
        ],
        "clustering_fields": ["assessment_id"],
    },
    "load_batches": {
        "schema": [
            SchemaField("batch_id", "STRING", mode="REQUIRED"),
            SchemaField("client_id", "STRING", mode="REQUIRED"),
            SchemaField("activity_type", "STRING", mode="REQUIRED"),
            SchemaField("source_file", "STRING"),
            SchemaField("load_mode", "STRING"),
            SchemaField("rows_read", "INT64"),
            SchemaField("rows_loaded", "INT64"),
            SchemaField("rows_rejected", "INT64"),
            SchemaField("status", "STRING"),
            SchemaField("started_at", "TIMESTAMP"),
            SchemaField("finished_at", "TIMESTAMP"),
        ],
        "time_partitioning": {"field": "started_at", "type_": "MONTH"},
    },
    "rejected_rows": {
        "schema": [
            SchemaField("batch_id", "STRING", mode="REQUIRED"),
            SchemaField("client_id", "STRING"),
            SchemaField("source_file", "STRING"),
            SchemaField("row_number", "INT64"),
            SchemaField("raw_row", "STRING"),
            SchemaField("validation_error", "STRING"),
            SchemaField("rejected_at", "TIMESTAMP"),
        ],
        "time_partitioning": {"field": "rejected_at", "type_": "MONTH"},
    },
}
